version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parcel-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
